### ISSUE TITLE
support for 'ogg chapters' in audio book files

### ISSUE THREAD

**Issue by dbojan** [Ph1b/MaterialAudiobookPlayer#173]
Hi.
Could you add support for 'ogg chapters' in audio book files?
They are basically tags with chapter start time and chapter name, and can also include cover art.

https://wiki.xiph.org/Chapter_Extension

Ogg chapters format are used in .opus and .ogg/.oga files.
Chapter marks can be added using VorbisComment , ffmpeg, or mp3tag programs.

There are also mka and m4b formats with chapters.

Example files:
MP4 (M4A), MP3, Ogg Vorbis, Opus:
https://auphonic.com/blog/2013/07/03/chapter-marks-and-enhanced-podcasts/

Mka:
https://onedrive.live.com/redir?resid=d3221cfe195f835b%2117170

M4b without cover:
http://wiki.librivox.org/index.php/M4B_Catalog

M4b with cover:
http://www.naxosaudiobooks.com/m4b.htm

Thank you.

**Comment by Ph1b** [comment]
For Opus there is a bug in Android which mostly  prevents opus files from playing.

I dont really know a good way to integrate chapters since the whole player is based on using files. If it was just one file, that would be no problem, but I see the importance too low to integrate this. If someone wants to write it, do it ;-)

**Comment by dbojan** [comment]
Are you talking about external text files for chapter info?
Chapters are added inside the audio file, as metada. They are not separate txt files. If that is what you mean.
One file for the whole book, with chapter marks inside it.

BR,
