### ISSUE TITLE
on locked screen inconsistent buttons

### ISSUE THREAD

**Issue by thofrey** [Ph1b/MaterialAudiobookPlayer#185]
On the locked screen I have the three buttons 'back to start', 'pause/play', 'forward to next chapter'.
But the back/forward functions seem to work as fast-back, fast-forward.

**Comment by Ph1b** [comment]
The thing is that these buttons are not customizable. Android provides them and I just use them. I directed the next / previous buttons to skip buttons since audiobooks are more based on a global position instead of jumping within tracks.
From Lollipop on (Android 5.0) we can use the normal notification as a lockscreen control, so there everything matches.
