### ISSUE TITLE
Remove book

### ISSUE THREAD

**Issue by skynetua** [Ph1b/MaterialAudiobookPlayer#281]
Are you considering to add option to remove book from app and all corresponding files from storage?

**Comment by Ph1b** [comment]
Nope. I want the app for playback only to not confuse the user and make them accidentally delete files.

**Comment by JoachimR** [comment]
i implemented a version of it for me
https://github.com/JoachimR/MaterialAudiobookPlayer/tree/deleteitem

i do not handle the android 4.4+ file permission stuff so it might not work on your phone. Since it is not intended for the master branch anyway I didn't bother figuring out this permission mess. Works for my phone :)
