### ISSUE TITLE
Android 6.0 preview 3 not allowing to select root folder

### ISSUE THREAD

**Issue by jmorones** [Ph1b/MaterialAudiobookPlayer#306]
I installed this application in my Nexus 6 running Android 6.0 Developer Preview 3 and when I try to set the root folder I get a screen that shows a label with the text "Chosen folder:" a "Cancel" button and a disabled "Set" button, nothing else, no way to set the folder and obviously no way to use the app afterwards...

**Comment by Ph1b** [comment]
Thanks for the report.

In theory this should be fixed as of 79e1a0f82d8806216a339a2f37e1cf04714b4bf6

The problem here is that currently there is a bug that leads to the fact that after the first permission granting, the permission is only granted after an app restart. You can find the bug [here](https://code.google.com/p/android-developer-preview/issues/detail?id=2982&q=Type%3DDefect&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars).

So after a restart [this preview build](https://www.dropbox.com/s/crv5flfvh5gcl2d/audiobook-debug-74-74-preview.apk?dl=0) should work. Can you test the flow and tell me how it worked for you?

**Comment by jmorones** [comment]
Sorry, I didn’t try your build, I ended up setting the permissions for the app through the android settings menu. It did work for me that way.

From: Paul Woitaschek
Reply-To: Ph1b/MaterialAudiobookPlayer
Date: Saturday, September 12, 2015 at 11:46
To: Ph1b/MaterialAudiobookPlayer
Cc: "Morones, Jesus"
Subject: Re: [MaterialAudiobookPlayer] Android 6.0 preview 3 not allowing to select root folder (#306)


Thanks for the report.

In theory this should be fixed as of 79e1a0f<https://github.com/Ph1b/MaterialAudiobookPlayer/commit/79e1a0f82d8806216a339a2f37e1cf04714b4bf6>

The problem here is that currently there is a bug that leads to the fact that after the first permission granting, the permission is only granted after an app restart. You can find the bug here<https://code.google.com/p/android-developer-preview/issues/detail?id=2982&q=Type%3DDefect&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars>.

So after a restart this preview build<https://www.dropbox.com/s/crv5flfvh5gcl2d/audiobook-debug-74-74-preview.apk?dl=0> should work. Can you test the flow and tell me how it worked for you?

**Comment by Ph1b** [comment]
Can you try it?

It's a develop build which can be installed along. It does not replace the production build or touch its settings.

**Comment by jmorones** [comment]
Tried it,
This time I got the permission request pop up, clicked allow and ended up in the same screen (only cancel was enabled).
Canceled and tried setting the folder again and this time it worked.

Hope that is helpful for you.

From: Paul Woitaschek
Reply-To: Ph1b/MaterialAudiobookPlayer
Date: Tuesday, September 15, 2015 at 01:19
To: Ph1b/MaterialAudiobookPlayer
Cc: "Morones, Jesus"
Subject: Re: [MaterialAudiobookPlayer] Android 6.0 preview 3 not allowing to select root folder (#306)


Can you try it?

It's a develop build which can be installed along. It does not replace the production build or touch its settings.
