### ISSUE TITLE
Cloud Support

### ISSUE THREAD

**Issue by sanicki** [Ph1b/MaterialAudiobookPlayer#52]
Please consider allowing streaming from Dropbox, Google Drive, Box, etc.

**Comment by Ph1b** [comment]
This seems to be too complicated, sorry.

**Comment by erolfox** [comment]
This app has done cloud support: https://play.google.com/store/apps/details?id=org.vadel.audiolibrary&hl=en

It was my prefered player because of this, all my audiobooks in Google Drive, but seems abandoned since Nov. 2013.

I think GDrive would be most important, as it's part of the ecosystem. Bet you could figure it out!
